import { DUNGEON_THEME_COLORS } from "@/shared/config";

import type { EnemyBehaviorState } from "./enemyMachineStates";
import { ENEMY_MACHINE_STATES } from "./enemyMachineStates";

export const ENEMY_COLLIDER_CONFIG = {
	HALF_HEIGHT: 0.67,
	RADIUS: 0.24,
} as const;

export const ENEMY_SPAWN_HEIGHT_OFFSET = 0.91;
export const ENEMY_SPAWN_OFFSET_XZ = 4;
export const ENEMY_PATROL_REACH_THRESHOLD = 0.3;
export const ENEMY_PATROL_RADIUS = 3.0;

export const ENEMY_GLOW_CONFIG = {
	RADIUS: 0.32,
	TUBE_RADIUS: 0.04,
	RADIAL_SEGMENTS: 18,
	TUBULAR_SEGMENTS: 28,
	ROTATION_X_RAD: Math.PI / 2,
	MATERIAL_OPACITY: 0.75,
} as const;

const ENEMY_PLAYER_TRACKING_CONFIG = {
	POSITION_THRESHOLD: 0.35,
	UPDATE_INTERVAL_MS: 120,
} as const;

export const ENEMY_ENTITY_CONFIG = {
	COLLIDER: ENEMY_COLLIDER_CONFIG,
	PHYSICS: {
		LINEAR_DAMPING: 8,
		ROTATION_SPEED: 8,
		MOVEMENT_THRESHOLD: 0.01,
	},
	PLAYER_TRACKING: ENEMY_PLAYER_TRACKING_CONFIG,
	BODY: {
		RADIUS: 0.22,
		HEIGHT: 0.85,
		POSITION_Y: 0.43,
		RADIAL_SEGMENTS: 14,
		COLOR: DUNGEON_THEME_COLORS.RUNE_SEALED,
		ROUGHNESS: 0.72,
		METALNESS: 0.18,
	},
	HEAD: {
		RADIUS: 0.16,
		OFFSET_Y: 0.88,
		WIDTH_SEGMENTS: 14,
		HEIGHT_SEGMENTS: 14,
		COLOR: DUNGEON_THEME_COLORS.TORCH_FLAME,
	},
	GLOW: {
		...ENEMY_GLOW_CONFIG,
		OFFSET_Y: -0.87,
	},
} as const;

export const ENEMY_GLOW_COLORS_BY_STATE: Record<EnemyBehaviorState, string> = {
	[ENEMY_MACHINE_STATES.PATROL]: DUNGEON_THEME_COLORS.RUNE_SEALED,
	[ENEMY_MACHINE_STATES.DETECT]: DUNGEON_THEME_COLORS.TORCH_FLAME,
	[ENEMY_MACHINE_STATES.CHASE]: DUNGEON_THEME_COLORS.RUNE_OPEN,
	[ENEMY_MACHINE_STATES.ATTACK]: DUNGEON_THEME_COLORS.RUNE_ACTIVE,
	[ENEMY_MACHINE_STATES.DEAD]: DUNGEON_THEME_COLORS.FOG_BASE,
};

export const ENEMY_GLOW_EMISSIVE_INTENSITY_BY_STATE: Record<
	EnemyBehaviorState,
	number
> = {
	[ENEMY_MACHINE_STATES.PATROL]: 0.4,
	[ENEMY_MACHINE_STATES.DETECT]: 0.9,
	[ENEMY_MACHINE_STATES.CHASE]: 1.2,
	[ENEMY_MACHINE_STATES.ATTACK]: 1.8,
	[ENEMY_MACHINE_STATES.DEAD]: 0.05,
};
