export const AUDIO_PROVIDER_UNLOCK_EVENTS = {
	POINTER_DOWN: "pointerdown",
	KEY_DOWN: "keydown",
	TOUCH_START: "touchstart",
} as const;

export const AUDIO_PROVIDER_UNLOCK_EVENT_LIST = [
	AUDIO_PROVIDER_UNLOCK_EVENTS.POINTER_DOWN,
	AUDIO_PROVIDER_UNLOCK_EVENTS.KEY_DOWN,
	AUDIO_PROVIDER_UNLOCK_EVENTS.TOUCH_START,
] as const;
