export const AUDIO_PROVIDER_UNLOCK_EVENTS = {
	POINTER_DOWN: "pointerdown",
	KEY_DOWN: "keydown",
} as const;

export const AUDIO_PROVIDER_UNLOCK_EVENT_LIST = [
	AUDIO_PROVIDER_UNLOCK_EVENTS.POINTER_DOWN,
	AUDIO_PROVIDER_UNLOCK_EVENTS.KEY_DOWN,
] as const;
