import { HAPTIC_EVENT_NAMES, type HapticEventName } from "./hapticEvents";
import type { HapticPatternKey } from "./hapticPatterns";

export const HAPTIC_EVENT_PATTERN_KEYS: Record<
	HapticEventName,
	HapticPatternKey
> = {
	[HAPTIC_EVENT_NAMES.ON_ROOM_ENTER]: "ROOM_ENTER",
	[HAPTIC_EVENT_NAMES.ON_GUARD_SUCCESS]: "GUARD_SUCCESS",
	[HAPTIC_EVENT_NAMES.ON_GUARD_FAIL]: "GUARD_FAIL",
	[HAPTIC_EVENT_NAMES.ON_ENEMY_HIT]: "ENEMY_HIT",
	[HAPTIC_EVENT_NAMES.ON_PLAYER_DEATH]: "PLAYER_DEATH",
	[HAPTIC_EVENT_NAMES.ON_KEY_PICKUP]: "KEY_PICKUP",
	[HAPTIC_EVENT_NAMES.ON_CAMERA_SWITCH]: "CAMERA_SWITCH",
	[HAPTIC_EVENT_NAMES.ON_TRANSITION]: "TRANSITION_FIRE",
	[HAPTIC_EVENT_NAMES.ON_ACHIEVEMENT]: "ACHIEVEMENT",
	[HAPTIC_EVENT_NAMES.ON_FLOOR_COMPLETE]: "FLOOR_COMPLETE",
};
