import type {
	CreateGamePageViewModelInput,
	GamePageViewModel,
} from "../model/types";

export const createGamePageViewModel = ({
	actionButtons,
	activeStateLabel,
	cameraStateSnapshot,
	currentRoomId,
	currentRoomLabel,
	discoveredRoomLabels,
	enemiesRemaining,
	graphSections,
	handleAudioMuteToggle,
	handleCameraModeSwitch,
	handleDungeonRunReset,
	handleMobileSheetOpenChange,
	handleMobileSheetTabChange,
	handleTouchAttack,
	handleTouchInteract,
	handleTouchJoystickMove,
	handleTouchJoystickStop,
	hasTouchAttack,
	hasTouchInteract,
	hasTreasureKey,
	hasTreasureKeyLabel,
	isAudioMuted,
	isDesktopLayout,
	isMobileSheetOpen,
	isMobileTabletLandscape,
	isTabletLayout,
	mobileSheetTabId,
	playerHp,
	playerMaxHp,
	touchAttackPrompt,
	touchInteractPrompt,
}: CreateGamePageViewModelInput): GamePageViewModel => {
	return {
		actionButtons,
		activeStateLabel,
		cameraStateSnapshot,
		canvasMachineRuntime: {
			currentRoomId,
			enemiesRemaining,
			hasTreasureKey,
		},
		currentRoomLabel,
		discoveredRoomLabels,
		enemiesRemaining,
		graphSections,
		handleAudioMuteToggle,
		handleCameraModeSwitch,
		handleDungeonRunReset,
		handleMobileSheetOpenChange,
		handleMobileSheetTabChange,
		handleTouchAttack,
		handleTouchInteract,
		handleTouchJoystickMove,
		handleTouchJoystickStop,
		hasTouchAttack,
		hasTouchInteract,
		hasTreasureKeyLabel,
		isAudioMuted,
		isDesktopLayout,
		isMobileSheetOpen,
		isMobileTabletLandscape,
		isTabletLayout,
		mobileSheetTabId,
		playerHp,
		playerMaxHp,
		touchAttackPrompt,
		touchInteractPrompt,
	};
};
