import { CORRIDOR_CONFIG } from "@/shared/config";

export const CORRIDOR_DIRECTIONS = {
	NORTH: "north",
	EAST: "east",
	SOUTH: "south",
	WEST: "west",
} as const;

export const CORRIDOR_DIRECTION_ORDER = [
	CORRIDOR_DIRECTIONS.NORTH,
	CORRIDOR_DIRECTIONS.EAST,
	CORRIDOR_DIRECTIONS.SOUTH,
	CORRIDOR_DIRECTIONS.WEST,
] as const;

export const CORRIDOR_ENTITY_CONFIG = {
	DIMENSIONS: {
		width: CORRIDOR_CONFIG.WIDTH,
		height: CORRIDOR_CONFIG.HEIGHT,
		depth: CORRIDOR_CONFIG.DEPTH,
		WALL_HEIGHT: 3,
	},
	GEOMETRY: {
		CENTER_OFFSET_DIVISOR: 2,
		HORIZONTAL_ROTATION_Y_RAD: Math.PI / 2,
	},
	SURFACE: {
		BASE_COLOR: "#2b3746",
		METALNESS: 0.14,
		ROUGHNESS: 0.86,
		SLAB_HEIGHT: 0.24,
		Y_OFFSET: -0.12,
	},
} as const;

export const CORRIDOR_FLOOR_COLLIDER = {
	HALF_HEIGHT: 0.3,
	POSITION_Y: -0.18,
} as const;

export const CORRIDOR_LIGHT_CONFIG = {
	INTENSITY: 4.6,
	DECAY: 2,
	HEIGHT: 2.0,
	COLOR: "#ffbb7a",
} as const;
