export {
	CORRIDOR_DIRECTION_ORDER,
	CORRIDOR_DIRECTIONS,
	CORRIDOR_ENTITY_CONFIG,
	CORRIDOR_FLOOR_COLLIDER,
	CORRIDOR_GLTF_CONFIG,
	CORRIDOR_HALF_WIDTH,
	CORRIDOR_LIGHT_CONFIG,
	CORRIDOR_WALL_Y,
} from "./corridorConfig";
