export {
	TUTORIAL_CONCEPT_ROWS,
	TUTORIAL_CONCEPTS_COPY,
	TUTORIAL_CONTROLS_COPY,
	TUTORIAL_COPY,
	TUTORIAL_DESKTOP_CONTROLS,
	TUTORIAL_FIRST_RUN_COPY,
	TUTORIAL_FIRST_RUN_STEPS,
	TUTORIAL_MOBILE_CONTROLS,
	TUTORIAL_TAB_IDS,
	TUTORIAL_TABS,
	type TutorialTabId,
} from "./tutorialCopy";
