export {
	TUTORIAL_CAMERA_MODES,
	TUTORIAL_CONTROL_GROUPS,
	TUTORIAL_CONTROLS_COPY,
	TUTORIAL_COPY,
	TUTORIAL_FIRST_RUN_COPY,
	TUTORIAL_FIRST_RUN_STEPS,
	TUTORIAL_FIRST_RUN_TONE_CLASS_NAMES,
	TUTORIAL_TAB_IDS,
	TUTORIAL_TABS,
	type TutorialTabId,
} from "./tutorialCopy";
