export const AUTH_EVENTS = {
	SESSION_BOOTSTRAPPED: "SESSION_BOOTSTRAPPED",
	SESSION_BOOTSTRAP_FAILED: "SESSION_BOOTSTRAP_FAILED",
	SESSION_BOOTSTRAP_RETRY_REQUESTED: "SESSION_BOOTSTRAP_RETRY_REQUESTED",
	USERNAME_SUBMIT_REQUESTED: "USERNAME_SUBMIT_REQUESTED",
	USERNAME_SUBMIT_SUCCEEDED: "USERNAME_SUBMIT_SUCCEEDED",
	USERNAME_SUBMIT_FAILED: "USERNAME_SUBMIT_FAILED",
	SIGN_OUT_REQUESTED: "SIGN_OUT_REQUESTED",
} as const;

export type AuthEventType = (typeof AUTH_EVENTS)[keyof typeof AUTH_EVENTS];
