import {
	CORRIDOR_CONFIG,
	DAGRE_CONFIG,
	ROOM_CONFIG,
	WORLD_SCALE_FACTOR,
} from "@/shared/config";

export const DUNGEON_GENERATOR_CONFIG = {
	CORRIDOR_HORIZONTAL_ROTATION_Y_RAD: Math.PI / 2,
	CORRIDOR_VERTICAL_ROTATION_Y_RAD: 0,
	DAGRE_DIRECTION: DAGRE_CONFIG.DIRECTION,
	DAGRE_NODE_HEIGHT: ROOM_CONFIG.DEPTH,
	DAGRE_NODE_WIDTH: ROOM_CONFIG.WIDTH,
	ROOM_SPACING: ROOM_CONFIG.WIDTH + CORRIDOR_CONFIG.DEPTH,
	WORLD_POSITION_Y: 0,
	WORLD_SCALE_FACTOR,
} as const;
