import { DAGRE_CONFIG, WORLD_SCALE_FACTOR } from "@/shared/config";

export const DUNGEON_GENERATOR_CONFIG = {
	CORRIDOR_HORIZONTAL_ROTATION_Y_RAD: 1.571,
	CORRIDOR_VERTICAL_ROTATION_Y_RAD: 0,
	DAGRE_DIRECTION: DAGRE_CONFIG.DIRECTION,
	DAGRE_NODE_HEIGHT: 12,
	DAGRE_NODE_WIDTH: 12,
	ROOM_SPACING: 20,
	WORLD_POSITION_Y: 0,
	WORLD_SCALE_FACTOR,
} as const;
