export const CAMERA_RIG_LERP_ALPHA = 0.0769;

export const CAMERA_RIG_FOV_EPSILON = 0.01;

export const CAMERA_RIG_FIRST_PERSON_TARGET_DISTANCE = 0.01;

export const CAMERA_RIG_FIRST_PERSON_FIXED_ORBIT_DISTANCE = 0.01;

export const CAMERA_RIG_FIRST_PERSON_LOOK_AHEAD_DISTANCE = 1;

export const CAMERA_RIG_EULER_ORDERS = {
	FIRST_PERSON_MOBILE: "YXZ",
} as const;

export const CAMERA_RIG_TRANSITION_JUMP_DISTANCE = 6;

export const CAMERA_RIG_THIRD_PERSON_TRANSITION_PADDING = 0.2;

export const CAMERA_RIG_FREE_ORBITAL_RECENTER_DISTANCE =
	CAMERA_RIG_TRANSITION_JUMP_DISTANCE;

export const CAMERA_RIG_MOBILE_TOP_DOWN_HEIGHT_SCALE = 0.75;

export const CAMERA_RIG_MOBILE_FREE_ORBITAL_OFFSET_SCALE = 0.8;

export const CAMERA_RIG_FIRST_PERSON_MOBILE_LOOK_LERP_ALPHA = 0.42;

export const CAMERA_RIG_CAMERA_UP = {
	DEFAULT: [0, 1, 0],
	TOP_DOWN: [0, 0, 1],
} as const;

export const CAMERA_RIG_TOUCH_GESTURES = {
	ORBIT: {
		ONE: 0,
		TWO: 2,
	},
	TOP_DOWN: {
		ONE: 1,
		TWO: 2,
	},
} as const;
