export const CAMERA_RIG_LERP_ALPHA = 0.0769;

export const CAMERA_RIG_TRANSITION_JUMP_DISTANCE = 6;

export const CAMERA_RIG_THIRD_PERSON_TRANSITION_PADDING = 0.2;

export const CAMERA_RIG_FREE_ORBITAL_RECENTER_DISTANCE =
	CAMERA_RIG_TRANSITION_JUMP_DISTANCE;

export const CAMERA_RIG_CAMERA_UP = {
	DEFAULT: [0, 1, 0],
	TOP_DOWN: [0, 0, 1],
} as const;

export const CAMERA_RIG_TOUCH_GESTURES = {
	ORBIT: {
		ONE: 0,
		TWO: 2,
	},
	TOP_DOWN: {
		ONE: 1,
		TWO: 2,
	},
} as const;
