import {
	DUNGEON_RUNE_STATES,
	DUNGEON_THEME,
	type DungeonRuneState,
	ROOM_IDS,
	type RoomId,
} from "@/entities/dungeon";

const CANVAS_FOG_DENSITY_MULTIPLIERS_BY_ROOM: Record<RoomId, number> = {
	[ROOM_IDS.ENTRANCE]: 0.84,
	[ROOM_IDS.LIBRARY]: 0.9,
	[ROOM_IDS.GUARD_ROOM]: 1,
	[ROOM_IDS.TREASURY]: 0.74,
	[ROOM_IDS.EXIT]: 0.62,
};

const CANVAS_RUNE_EMISSIVE_MULTIPLIERS: Record<DungeonRuneState, number> = {
	[DUNGEON_RUNE_STATES.SEALED]: 0.3,
	[DUNGEON_RUNE_STATES.OPEN]: 0.75,
	[DUNGEON_RUNE_STATES.ACTIVE]: 1.2,
};

const CANVAS_TORCH_INTENSITY_CONFIG = {
	ENEMY_STEP: 0.5,
	MIN: 1,
	MAX: 2,
} as const;

const CANVAS_FREE_ORBITAL_TORCH_ROOM_LIMIT = 2;

const CANVAS_RUNE_COLORS_BY_STATE: Record<
	DungeonRuneState,
	{
		activeColor: string;
		emissiveColor: string;
	}
> = {
	[DUNGEON_RUNE_STATES.SEALED]: {
		activeColor: DUNGEON_THEME.RUNES.SEALED,
		emissiveColor: DUNGEON_THEME.RUNES.SEALED,
	},
	[DUNGEON_RUNE_STATES.OPEN]: {
		activeColor: DUNGEON_THEME.RUNES.OPEN,
		emissiveColor: DUNGEON_THEME.RUNES.OPEN,
	},
	[DUNGEON_RUNE_STATES.ACTIVE]: {
		activeColor: DUNGEON_THEME.RUNES.ACTIVE,
		emissiveColor: DUNGEON_THEME.RUNES.ACTIVE,
	},
};

export {
	CANVAS_FOG_DENSITY_MULTIPLIERS_BY_ROOM,
	CANVAS_FREE_ORBITAL_TORCH_ROOM_LIMIT,
	CANVAS_RUNE_COLORS_BY_STATE,
	CANVAS_RUNE_EMISSIVE_MULTIPLIERS,
	CANVAS_TORCH_INTENSITY_CONFIG,
};
