import { ENEMY_SPAWN_HEIGHT_OFFSET } from "@/entities/enemy";
import { ROOM_ENTITY_CONFIG } from "@/entities/room";

export const WORLD_INTERACTION_PROMPT_CONFIG = {
	DISTANCE_FACTOR: 12,
	DOOR_HEIGHT: ROOM_ENTITY_CONFIG.DOORWAY_GATE.POSITION_Y,
	ENEMY_HEIGHT_OFFSET: ENEMY_SPAWN_HEIGHT_OFFSET + 0.45,
	KEY_HEIGHT: ROOM_ENTITY_CONFIG.TREASURE_KEY.HEIGHT + 1.35,
} as const;
