export const PLAYER_MOVEMENT_KEYS = {
	FORWARD: "w",
	BACKWARD: "s",
	LEFT: "a",
	RIGHT: "d",
} as const;

export type PlayerMovementKey =
	(typeof PLAYER_MOVEMENT_KEYS)[keyof typeof PLAYER_MOVEMENT_KEYS];

export const PLAYER_MOVEMENT_KEY_ALIASES = {
	w: PLAYER_MOVEMENT_KEYS.FORWARD,
	W: PLAYER_MOVEMENT_KEYS.FORWARD,
	ArrowUp: PLAYER_MOVEMENT_KEYS.FORWARD,
	s: PLAYER_MOVEMENT_KEYS.BACKWARD,
	S: PLAYER_MOVEMENT_KEYS.BACKWARD,
	ArrowDown: PLAYER_MOVEMENT_KEYS.BACKWARD,
	a: PLAYER_MOVEMENT_KEYS.LEFT,
	A: PLAYER_MOVEMENT_KEYS.LEFT,
	ArrowLeft: PLAYER_MOVEMENT_KEYS.LEFT,
	d: PLAYER_MOVEMENT_KEYS.RIGHT,
	D: PLAYER_MOVEMENT_KEYS.RIGHT,
	ArrowRight: PLAYER_MOVEMENT_KEYS.RIGHT,
} as const;

export const PLAYER_MOVEMENT_DIRECTIONS = {
	[PLAYER_MOVEMENT_KEYS.FORWARD]: [0, 0, -1] as const,
	[PLAYER_MOVEMENT_KEYS.BACKWARD]: [0, 0, 1] as const,
	[PLAYER_MOVEMENT_KEYS.LEFT]: [-1, 0, 0] as const,
	[PLAYER_MOVEMENT_KEYS.RIGHT]: [1, 0, 0] as const,
} as const;
