import { DUNGEON_THEME_COLORS } from "@/shared/config";
import type { Vector3Tuple } from "@/shared/lib";

import { PLAYER_STATES } from "./playerStates";

const PLAYER_ORIGIN: Vector3Tuple = [0, 0, 0];

const PLAYER_CAPSULE_CONFIG = {
	HALF_HEIGHT: 0.55,
	RADIUS: 0.35,
} as const;

const PLAYER_SPAWN_HEIGHT_OFFSET = 0.9;

const PLAYER_DAMAGE_FLASH_DURATION_MS = 400;

export const PLAYER_ENTITY_CONFIG = {
	MOVEMENT: {
		SPEED: 7,
		SPRINT_SPEED: 11,
		ROTATION_SPEED: 10,
	},
	ORIGIN: PLAYER_ORIGIN,
	DEFAULTS: {
		HEALTH_STATE: PLAYER_STATES.HEALTH.ALIVE,
	},
	CAPSULE: PLAYER_CAPSULE_CONFIG,
	PHYSICS: {
		LINEAR_DAMPING: 12,
	},
	TRANSFORM: {
		SPAWN_HEIGHT_OFFSET: PLAYER_SPAWN_HEIGHT_OFFSET,
	},
	BODY: {
		COLOR: DUNGEON_THEME_COLORS.ROOM_LABEL,
		HEIGHT: 1.5,
		METALNESS: 0.22,
		POSITION_Y: 0.75,
		RADIUS: 0.38,
		RADIAL_SEGMENTS: 16,
		ROUGHNESS: 0.56,
	},
	HEAD: {
		COLOR: DUNGEON_THEME_COLORS.RUNE_OPEN,
		HEIGHT_SEGMENTS: 16,
		OFFSET_Y: 1.65,
		RADIUS: 0.26,
		WIDTH_SEGMENTS: 16,
	},
	DAMAGE_FLASH_DURATION_MS: PLAYER_DAMAGE_FLASH_DURATION_MS,
} as const;
