export {
	HOME_COPY,
	HOME_FEATURES,
	HOME_MANIFEST_FOCUS_ITEM,
	HOME_MANIFEST_MAP_NODES,
	HOME_MANIFEST_TONE_CLASS_NAMES,
	HOME_RUNTIME_PANELS,
	HOME_STATUS_COPY,
	HOME_TEACHING_TONE_CLASS_NAMES,
	HOME_TRANSLATION_ARROW_CLASS_NAME,
	HOME_TRANSLATION_RAIL,
	HOME_TRANSLATION_TONE_CLASS_NAMES,
} from "./homeCopy";
