export const MACHINE_GRAPH_LAYOUT = {
	DIRECTION: "TB",
	NODE_WIDTH: 160,
	NODE_HEIGHT: 60,
	NODE_SEPARATION: 56,
	RANK_SEPARATION: 92,
} as const;

export const STATE_VISUALIZER_SECTION_IDS = {
	DUNGEON: "dungeon",
	CAMERA: "camera",
	AUDIO: "audio",
	PLAYER: "player",
} as const;

export const STATE_VISUALIZER_GRAPH_SYNTAX = {
	GUARD_DELIMITER: " & ",
	EDGE_FLOW_SEPARATOR: " -> ",
	EDGE_PAIR_SEPARATOR: "|",
	EDGE_ID_SEGMENT_SEPARATOR: ":",
	NODE_PATH_SEPARATOR: ".",
	TARGET_ID_PREFIX: "#",
	RELATIVE_TARGET_PREFIX: ".",
	MACHINE_GUARD_PREFIX: "xstate.",
	UNGUARDED_EDGE_TOKEN: "unguarded",
	STATE_PATH_DELIMITER: " | ",
	GUARD_LABEL_CAPTURE_PATTERN: /\[(.+?)\]/,
	GUARD_TOKEN_SPLIT_PATTERN: /&&|\band\b|&|,/gi,
} as const;

export const STATE_VISUALIZER_NODE_KINDS = {
	STATE: "state",
	INITIAL: "initial",
	FINAL: "final",
} as const;

export const STATE_VISUALIZER_SECTIONS: Array<{
	id: (typeof STATE_VISUALIZER_SECTION_IDS)[keyof typeof STATE_VISUALIZER_SECTION_IDS];
	label: string;
}> = [
	{ id: STATE_VISUALIZER_SECTION_IDS.DUNGEON, label: "Dungeon" },
	{ id: STATE_VISUALIZER_SECTION_IDS.CAMERA, label: "Camera" },
	{ id: STATE_VISUALIZER_SECTION_IDS.AUDIO, label: "Audio" },
	{ id: STATE_VISUALIZER_SECTION_IDS.PLAYER, label: "Player" },
] as const;

export const STATE_VISUALIZER_DEFAULT_OPEN_SECTION =
	STATE_VISUALIZER_SECTION_IDS.DUNGEON;
