export const GAME_FRAME_PRIORITIES = {
	PLAYER_PRE_PHYSICS_MOTION: -5,
	PHYSICS_STEP: -4,
	PLAYER_POST_PHYSICS_SNAPSHOT: -3,
	PLAYER_CAMERA_FOLLOW_POSITION_SYNC: -2.5,
	CAMERA_FOLLOW_SYNC: -2,
} as const;
