export const TOUCH_JOYSTICK_CONFIG = {
	CONTAINER_SIZE_PX: 132,
	CONTAINER_SIZE_CLASS_NAME: "h-[132px] w-[132px]",
	KNOB_SIZE_PX: 56,
	KNOB_SIZE_CLASS_NAME: "h-[56px] w-[56px]",
	MAX_RADIUS_PX: 44,
	DEAD_ZONE_RATIO: 0.2,
} as const;
