export const TOUCH_JOYSTICK_CONFIG = {
	CONTAINER_SIZE_PX: 176,
	KNOB_SIZE_PX: 72,
	MAX_RADIUS_PX: 52,
	DEAD_ZONE_RATIO: 0.2,
	VELOCITY_CHANGE_THRESHOLD: 0.01,
	RESTING_KNOB_OFFSET_PX: 0,
} as const;
