export {
	INSPECTOR_COPY,
	INSPECTOR_EDGE_LABELS,
	INSPECTOR_FLOW_EDGE_LAYOUT,
	INSPECTOR_FLOW_EDGE_VISUALS,
	INSPECTOR_FLOW_NODE_VISUALS,
	INSPECTOR_REACT_FLOW_DEFAULTS,
	INSPECTOR_REACT_FLOW_SECTION_PADDING,
} from "./inspectorGraphConfig";
