export { INSPECTOR_DETAILS_PANEL_IDS } from "./inspectorDetailsPanelConfig";
export {
	INSPECTOR_COPY,
	INSPECTOR_EDGE_LABELS,
	INSPECTOR_FLOW_BACKGROUND,
	INSPECTOR_FLOW_EDGE_LAYOUT,
	INSPECTOR_FLOW_EDGE_VISUALS,
	INSPECTOR_GUARD_LEGEND_LAYOUT,
	INSPECTOR_GUARD_MARKER_INTERACTION,
	INSPECTOR_ID_SEGMENT_SEPARATOR,
	INSPECTOR_ID_SEGMENTS,
	INSPECTOR_REACT_FLOW_DEFAULTS,
	INSPECTOR_REACT_FLOW_SECTION_PADDING,
} from "./inspectorGraphConfig";
