import { DUNGEON_EVENTS, ROOM_IDS, type RoomId } from "@/entities/dungeon";

export const NAVIGATION_ACTION_EVENTS = [
	DUNGEON_EVENTS.ENTER_LIBRARY,
	DUNGEON_EVENTS.ENTER_GUARD_ROOM,
	DUNGEON_EVENTS.PICK_UP_KEY,
	DUNGEON_EVENTS.ENEMY_DIED,
	DUNGEON_EVENTS.ENTER_TREASURY,
	DUNGEON_EVENTS.ENTER_EXIT,
	DUNGEON_EVENTS.RETURN_TO_ENTRANCE,
	DUNGEON_EVENTS.RETURN_TO_GUARD_ROOM,
] as const;

export type NavigationActionEvent = (typeof NAVIGATION_ACTION_EVENTS)[number];

export const NAVIGATION_ACTION_LABELS: Record<NavigationActionEvent, string> = {
	[DUNGEON_EVENTS.ENTER_LIBRARY]: "Enter Library",
	[DUNGEON_EVENTS.ENTER_GUARD_ROOM]: "Enter Guard Room",
	[DUNGEON_EVENTS.PICK_UP_KEY]: "Pick Up Key",
	[DUNGEON_EVENTS.ENEMY_DIED]: "Defeat Enemy",
	[DUNGEON_EVENTS.ENTER_TREASURY]: "Enter Treasury",
	[DUNGEON_EVENTS.ENTER_EXIT]: "Enter Exit",
	[DUNGEON_EVENTS.RETURN_TO_ENTRANCE]: "Return to Entrance",
	[DUNGEON_EVENTS.RETURN_TO_GUARD_ROOM]: "Return to Guard Room",
};

export const ROOM_LABELS: Record<RoomId, string> = {
	[ROOM_IDS.ENTRANCE]: "Entrance",
	[ROOM_IDS.LIBRARY]: "Library",
	[ROOM_IDS.GUARD_ROOM]: "Guard Room",
	[ROOM_IDS.TREASURY]: "Treasury",
	[ROOM_IDS.EXIT]: "Exit",
};
