import {
	DOOR_SIDES,
	type DoorSide,
	DUNGEON_EVENTS,
	ROOM_IDS,
	type RoomId,
} from "@/entities/dungeon";

export const NAVIGATION_ACTION_EVENTS = [
	DUNGEON_EVENTS.ENTER_LIBRARY,
	DUNGEON_EVENTS.ENTER_GUARD_ROOM,
	DUNGEON_EVENTS.PICK_UP_KEY,
	DUNGEON_EVENTS.ENEMY_DIED,
	DUNGEON_EVENTS.ENTER_TREASURY,
	DUNGEON_EVENTS.ENTER_EXIT,
	DUNGEON_EVENTS.RETURN_TO_ENTRANCE,
	DUNGEON_EVENTS.RETURN_TO_LIBRARY,
	DUNGEON_EVENTS.RETURN_TO_GUARD_ROOM,
	DUNGEON_EVENTS.RETURN_TO_TREASURY,
] as const;

export type NavigationActionEvent = (typeof NAVIGATION_ACTION_EVENTS)[number];

const DOOR_NAVIGATION_EVENTS = [
	DUNGEON_EVENTS.ENTER_LIBRARY,
	DUNGEON_EVENTS.ENTER_GUARD_ROOM,
	DUNGEON_EVENTS.ENTER_TREASURY,
	DUNGEON_EVENTS.ENTER_EXIT,
	DUNGEON_EVENTS.RETURN_TO_ENTRANCE,
	DUNGEON_EVENTS.RETURN_TO_LIBRARY,
	DUNGEON_EVENTS.RETURN_TO_GUARD_ROOM,
	DUNGEON_EVENTS.RETURN_TO_TREASURY,
] as const;

export type DoorNavigationEvent = (typeof DOOR_NAVIGATION_EVENTS)[number];

export const NAVIGATION_ACTION_LABELS: Record<NavigationActionEvent, string> = {
	[DUNGEON_EVENTS.ENTER_LIBRARY]: "Enter Library",
	[DUNGEON_EVENTS.ENTER_GUARD_ROOM]: "Enter Guard Room",
	[DUNGEON_EVENTS.PICK_UP_KEY]: "Pick Up Key",
	[DUNGEON_EVENTS.ENEMY_DIED]: "Defeat Enemy",
	[DUNGEON_EVENTS.ENTER_TREASURY]: "Enter Treasury",
	[DUNGEON_EVENTS.ENTER_EXIT]: "Enter Exit",
	[DUNGEON_EVENTS.RETURN_TO_ENTRANCE]: "Return to Entrance",
	[DUNGEON_EVENTS.RETURN_TO_LIBRARY]: "Return to Library",
	[DUNGEON_EVENTS.RETURN_TO_GUARD_ROOM]: "Return to Guard Room",
	[DUNGEON_EVENTS.RETURN_TO_TREASURY]: "Return to Treasury",
};

export const DOOR_TRANSITION_MAP: Record<
	DoorNavigationEvent,
	{ direction: DoorSide; roomId: RoomId }
> = {
	[DUNGEON_EVENTS.ENTER_LIBRARY]: {
		direction: DOOR_SIDES.SOUTH,
		roomId: ROOM_IDS.ENTRANCE,
	},
	[DUNGEON_EVENTS.ENTER_GUARD_ROOM]: {
		direction: DOOR_SIDES.SOUTH,
		roomId: ROOM_IDS.LIBRARY,
	},
	[DUNGEON_EVENTS.ENTER_TREASURY]: {
		direction: DOOR_SIDES.SOUTH,
		roomId: ROOM_IDS.GUARD_ROOM,
	},
	[DUNGEON_EVENTS.ENTER_EXIT]: {
		direction: DOOR_SIDES.SOUTH,
		roomId: ROOM_IDS.TREASURY,
	},
	[DUNGEON_EVENTS.RETURN_TO_ENTRANCE]: {
		direction: DOOR_SIDES.NORTH,
		roomId: ROOM_IDS.LIBRARY,
	},
	[DUNGEON_EVENTS.RETURN_TO_LIBRARY]: {
		direction: DOOR_SIDES.NORTH,
		roomId: ROOM_IDS.GUARD_ROOM,
	},
	[DUNGEON_EVENTS.RETURN_TO_GUARD_ROOM]: {
		direction: DOOR_SIDES.NORTH,
		roomId: ROOM_IDS.TREASURY,
	},
	[DUNGEON_EVENTS.RETURN_TO_TREASURY]: {
		direction: DOOR_SIDES.NORTH,
		roomId: ROOM_IDS.EXIT,
	},
} as const;
