export const DUNGEON_EVENTS = {
	ENTER_LIBRARY: "ENTER_LIBRARY",
	ENTER_GUARD_ROOM: "ENTER_GUARD_ROOM",
	ENTER_TREASURY: "ENTER_TREASURY",
	ENTER_EXIT: "ENTER_EXIT",
	PICK_UP_KEY: "PICK_UP_KEY",
	ENEMY_DIED: "ENEMY_DIED",
	LOCKED_DOOR_ATTEMPT: "LOCKED_DOOR_ATTEMPT",
	LOCKED_EXIT_ATTEMPT: "LOCKED_EXIT_ATTEMPT",
	RETURN_TO_ENTRANCE: "RETURN_TO_ENTRANCE",
	RETURN_TO_LIBRARY: "RETURN_TO_LIBRARY",
	RETURN_TO_GUARD_ROOM: "RETURN_TO_GUARD_ROOM",
	RETURN_TO_TREASURY: "RETURN_TO_TREASURY",
} as const;

export type DungeonEvent = (typeof DUNGEON_EVENTS)[keyof typeof DUNGEON_EVENTS];

export type DungeonEventObject = {
	type: DungeonEvent;
};
